### PR TITLE
Shrinking stuff

### PR DESCRIPTION
**Pull request by odino**
- using some netstat magic to get the dockerhost IP
- removed `ngrok_discover`
- touching `.ngrok` config file so that anyone can mount its own file through a volume (`-v .ngrok:/.ngrok`)

Not sure if the ngrok_discover script was doing something special or what, but I tried to simplify the whole process through a single command and that's what I came up with. Feedback is welcome, I might have missed something!

### CODE REVIEW

**Comment by patocox** [comment]
LGTM :+1:

**Comment by odino** [comment]
thanks man!

**Comment by odino** [comment]
Thanks! though I think the build on the hub is still the old one -- can you trigger a new manual build?

cheers!

**Comment by patocox** [comment]
oops. Didnt have that on automatic. Built now... thanks again!

**Comment by odino** [comment]
:+1:

**Pull request merged**
